### ISSUE TITLE
Sidenav not supporting (much) nesting

### ISSUE THREAD

**Issue by wendellpiez** [usnistgov/hugo-uswds#13]
In OSCAL docs production, we want to produce a nested table of contents through Hugo targeting particular elements in the HTML.

This can be done, as documented, in the YAML header (as in an example of `xml-schema.md`):

```yaml
sidenav:
  title: XML Format Reference
  toc:
    headingselectors: "h2.toc1, span.toc2"
```

But the ToC produced in this case is not nested. The `toc2` targets are listed next to the `toc1` targets, not "inside" them.

It appears to work if the value is given as `h2.toc1, h3.toc2`, and the page has `h3` instead of `span`.

However we don't want the entire line to be listed in the ToC (as a "header"), only the segment inside the line. `span` seems appropriate here to use for extraction of content into the ToC.

Any workarounds here? The problem with using the `h3` is that in USWDS, `h3` (any `h*`) implies all kinds of formatting logic for its siblings, and here the siblings are in line ... leading to side effects in the display requiring a lot of CSS to override. It would be nice it we could simply list the contents of the span.

**Comment by wendellpiez** [comment]
Found a way to do the CSS more simply than I thought so we are okay with this now.

**Comment by david-waltermire** [comment]
This was fixed long ago.
