### ISSUE TITLE
Define USWDS dependencies in a `package.json`

### ISSUE THREAD

**Issue by nikitawootten-nist** [usnistgov/hugo-uswds#30]
Currently the USWDS javascript dependencies are [vendored](https://github.com/usnistgov/hugo-uswds/tree/a869d8714313de05342ae1902276dfc6777633ab/assets) without any metadata about what version of USWDS the project relies upon.

I'd like to propose either:
1. Continue vendoring (committing assets to the main branch) the UWDS dependencies, but define the versions in a `package.json` and include a script to copy the relevant assets out of the `node_modules/` folder

    - This approach is easier to use, and allows consumers using the submodule method to still point at the `master` branch.
    - Actions will probably be required to prevent the vendored dependency from getting out of sync with the `package.json`

2. Make the process of building the website for consumption as a theme explicit. Commits to the main branch do not contain USWDS code, and users of the submodule point at a "built" branch.

    - This approach is "cleaner" as it does not include separate JS code in the main branches, which may lead to better scaling if more dependencies are added.
    - Actions will be required to "build" the module, committing to a separate branch.
    - For local development, a makefile (or insert your own helper here) will be required to copy the dependencies before building the docs site. 

Both of these approaches would allow for us to easily upgrade version of USWDS as well as any future dependencies we may want to include in the future.

This would also allow for integration with dependabot.

**Comment by david-waltermire** [comment]
This was completed in PR #35.
