### ISSUE TITLE
site-in-page-nav does not resize well in some circumstances

### ISSUE THREAD

**Issue by Chris-Turner-NIST** [usnistgov/hugo-uswds#36]
Image provided below as example. There is a lot of space left on the right side of the page, but the navigation section appears to have a strict width enforced. This particular widget appears to be hidden/culled on smaller screen representations making the reasoning for such a strict width unclear.

Can the width be adjustable or more flexible based on content? 
![MicrosoftTeams-image](https://github.com/usnistgov/hugo-uswds/assets/40207468/6da154e7-b32d-47fa-8762-ac1a7f9e8736)

**Comment by david-waltermire** [comment]
This was fixed in #37 .
